### ISSUE TITLE
Models ending with the character "s" are created without it

### ISSUE THREAD

**Issue by yonatan2703** [NangoHQ/nango#1441]
Nango CLI version: nango@0.36.56

I have the following nango.yaml file
```yaml
integrations:
    hubspot:
        get-lead-statuses:
            description: |
                Gets the lead statuses from Hubspot.
            type: action
            scopes: crm.objects.companies.read
            returns:
                - LeadStatus
        export-contact-and-company:
            description: |
                Exports a contact and company to Hubspot.
            type: action
            scopes: crm.objects.contacts.write crm.objects.companies.write
            returns: ExportContactAndCompany

models:
    LeadStatus:
        ok: boolean
        results: string[]
    ExportContactAndCompany:
        ok: boolean
        results: string[]
```

When I generate the relevant functions and models using the nango generate command from the CLI the models look like this:

```javascript
export interface LeadStatu {
  ok: boolean;
  results: string[];
}

export interface ExportContactAndCompany {
  ok: boolean;
  results: string[];
}
```

When I changed the name of the model to 'LeadStatusList' everything works
