### ISSUE TITLE
Upgrade from 0.36.14 to 0.42.8 fails with exception

### ISSUE THREAD

**Issue by sgrodzicki** [NangoHQ/nango#2686]
I'm experiencing issues when upgrading Nango from version `0.36.14` to `0.42.8`. The upgrade process seems to complete without errors, including database migrations. However, when I attempt to access the Nango UI, I encounter the following error message, indicating that there might be missing or incompatible migration scripts:

`server  | 14:35:12.035 error (ErrorManager) Exception caught Undefined binding(s) detected when compiling SELECT. Undefined column(s): [account_id] query: select "name" from "_nango_environments" where "account_id" = ? { message: 'Undefined binding(s) detected when compiling SELECT. Undefined column(s): [account_id] query: select "name" from "_nango_environments" where "account_id" = ?', name: 'Error', stack: 'Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [account_id] query: select "name" from "_nango_environments" where "account_id" = ?\n    at QueryCompiler_PG.toSQL (/usr/nango-server/src/node_modules/knex/lib/query/querycompiler.js:112:13)\n    at QueryBuilder_PostgreSQL.toSQL (/usr/nango-server/src/node_modules/knex/lib/query/querybuilder.js:84:44)\n    at ensureConnectionCallback (/usr/nango-server/src/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)\n    at Runner.ensureConnection (/usr/nango-server/src/node_modules/knex/lib/execution/runner.js:318:20)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Runner.run (/usr/nango-server/src/node_modules/knex/lib/execution/runner.js:30:19)\n    at async EnvironmentService.getEnvironmentsByAccountId (file:///usr/nango-server/src/packages/shared/dist/services/environment.service.js:14:28)\n    at async file:///usr/nango-server/src/packages/server/dist/controllers/v1/meta/getMeta.js:15:26' }`

I've tried to reproduce this issue on a clean installation of Nango 0.36.14 and then performing the upgrade to 0.42.8. The same error occurs.

## Steps to Reproduce:

1. Install Nango 0.36.14 on a clean environment (use the following `docker-compose.yaml` config).
1. Create an integration (e.g., `unauthenticated`) and a connection.
1. Upgrade Nango to 0.42.8 (swap images in the `docker-compose.yaml` config).
1. Attempt to access the Nango UI.
1. Observe the "It's not you, it's us." error message in the UI and detailed error logs in the console.

```yaml
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: nango
      POSTGRES_USER: nango
      POSTGRES_DB: nango
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nango
  server:
    container_name: server
    image: nangohq/nango-server:0.36.14
#    image: nangohq/nango-server:hosted
    platform: linux/amd64
    environment:
      NANGO_DB_HOST: db
      NANGO_DB_NAME: nango
      NANGO_DB_USER: nango
      NANGO_DB_PASSWORD: nango
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - nango

networks:
  nango:

volumes:
  db:
```

## Expected Behavior:

The upgrade process should complete successfully, and the Nango UI should function without errors.

## Possible Solutions:

- **Intermediate Release:** Is there an intermediate release between 0.36.14 and 0.42.8 that might resolve the compatibility issues?
- **Migration Script Issues:** Are there any known issues or workarounds related to migration scripts between these versions?
- **Configuration Errors:** Could there be configuration errors or conflicts that are preventing the migration scripts from executing correctly?

I'm open to providing more details or troubleshooting steps if needed.
