### ISSUE TITLE
Add support for Salesforce refresh token handling

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#327]
Salesforce OAuth flow has some uncommon handling of access token expiration, which makes it currently incompatible with Nango:
Instead of providing an `expires_at` entry for the expiration time in the token response, it just returns an access token and a refresh token.
To understand if the access token is expired you have two options:
* Listen for a 401 response from the API
* Query a specific endpoint that returns the expiration data of the access token.

Note that the expiration time of the access token can be set by the customer (along with an option to manually revoke it at any time).

These two methods are documented in more detail here: https://dev.to/xkit/when-do-salesforce-access-tokens-expire-1ih9#:~:text=Typical%20Token%20Expiration,any%20time%20with%20no%20warning.

Raw token response from Salesforce:
```json
{
"access_token": "REDACTED",
    "refresh_token": "REDACTED",
    "signature": "VA0jxT+xl3HUdw1+Fz2f+47OD3AV490hgNhhkFYvPLE=",
    "scope": "refresh_token full",
    "id_token": "REDACTED-HUGE-PROBABLY-JWT",
    "instance_url": "https://nango-dev-ed.develop.my.salesforce.com",
    "id": "https://login.salesforce.com/id/REDACTED/REDACTED",
    "token_type": "Bearer",
    "issued_at": "1676372418560"
 }
```

Template for providers.yaml (to be inserted above salesloft):
```yaml
salesforce:
    auth_mode: OAUTH2
    authorization_url: https://login.salesforce.com/services/oauth2/authorize
    token_url: https://login.salesforce.com/services/oauth2/token
```

DM me for credentials to test this with our Salesforce developer account.
