### ISSUE TITLE
TikTok

### ISSUE THREAD

**Issue by bastienbeurier** [NangoHQ/nango#352]
Requested by Krishna after signing up to Cloud.

**Comment by rguldener** [comment]
Implementing this requires deeper changes to the code: TikTok calls the `client_id` the `client_key` and if you don't pass it in with this parameter name the flow does not work. This is both for the authorization redirect and the access token retrieval.

Apart from this we should support everything for this OAuth flow as far as I can tell now.

Authorization redirect docs: https://developers.tiktok.com/doc/login-kit-web/
Access token docs: https://developers.tiktok.com/doc/login-kit-manage-user-access-tokens/

TikTok is stubborn about redirect domains, it doesn't take localhost. I recommend using this (together with a custom callback URL in .env): https://redirectmeto.com/

Stub of the providers.yaml:
```yaml
tiktok:
    auth_mode: OAUTH2
    authorization_url: https://www.tiktok.com/auth/authorize
    token_url: https://open-api.tiktok.com/oauth/access_token
    refresh_url: https://open-api.tiktok.com/oauth/refresh_token
```

I already created `tiktok.md` page in the docs, it just is not linked in the sidebar yet. When this is done the link should be added to sidebar.js

To add support we need to either make a change to the templates or implement a special clause for Tik Tok in the code somehow. Might also be a good moment to replace the SimpleOAuth2 library because it doesn't allow such deep changes like this one.
