### ISSUE TITLE
Docs typo in nango.yaml

### ISSUE THREAD

**Issue by khaliqgant** [NangoHQ/nango#722]
```
integrations:
	asana-dev: # Integration name (must match an Integration name in the Integrations tab of your Nango dashboard).
		asana-tasks: # Arbitrary Sync name
			runs: every 30min # Sync frequency
			return:
				- AsanaTask # Data model (defined below) as returned by your Sync script

models: 
	AsanaTask: # Data model referenced above
		id: string # Required unique ID
        project_id: string
        name: string
        completed: boolean
        created_at: date
 ```   
        
  
  Should be “returns” not “return”

https://docs.nango.dev/guides/sync — step 2

# Other Items To Note In Docs
* Model names must be singular. If not it will be stripped of the trailing `s`.
