### ISSUE TITLE
Detect connection config params in proxy base URL

### ISSUE THREAD

**Issue by rguldener** [NangoHQ/nango#822]
The frontend code snippet on the dashboard currently doesn't show connection params that are only used in the proxy API base URL.

Current UI:
![image](https://github.com/NangoHQ/nango/assets/682011/a355a85c-b305-403b-8a98-ba8bcfde25fb)

`providers.yaml` snippet:
```yaml
workable:
    auth_mode: API_KEY
    proxy:
        header:
            Authorization: Bearer ${apiKey}
        base_url: https://${connectionConfig.params.subdomain}.workable.com
```

Since this mentions a `subdomain` param the additional params field should be shown on the "Add connection" UI in the dashboard.
